controller:
  replicaCount: 3
  # config:
  #   ssl-redirect: "false" # we use `special` port to control ssl redirection
  #   server-snippet: |
  #     listen 2443;
  #     if ( $server_port = 80 ) {
  #        return 308 https://$host$request_uri;
  #     }
  # containerPort:
  #   http: 80
  #   https: 443
  #   tohttps: 2443
  service:
    targetPorts:
      http: http
      https: http
    annotations:
      # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      # service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-1:185437386355:certificate/5a0a8266-d384-4372-81a9-78dc59f7c217"
      # service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'