annotations:
  category: Application
apiVersion: v2
appVersion: 1.16.0
description: Appsmith is an open source framework to build admin panels, CRUD apps
  and workflows. Build everything you need, 10x faster.
home: https://www.appsmith.com/
icon: https://assets.appsmith.com/appsmith-icon.png
maintainers:
- email: tech@appsmith.com
  name: Appsmith
name: appsmith
sources:
- https://github.com/appsmithorg/appsmith
type: application
version: 1.5.3
